Imports que importam :) 

In [1]:
import numpy as np
import math

import pandas

In [2]:
from random import *
cutpart = lambda x: (int((x+1) * np.random.normal(scale=0.2,loc=0.5)) )% x

In [3]:
va = [x for x in range(1,11)]
vb = [x for x in range(10,0,-1)]
print("va:\n{}\nvb:\n{}".format(va,vb))

va:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
vb:
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


<h1>Genetic Algorithm for QAP solving()</h1>

In [4]:
def crossover(va,vb):
    cut = cutpart(len(va))
    print("cut: {}".format(cut))
    new_va = va[:cut]+vb[cut:]
    new_vb = vb[:cut]+va[cut:]
    print("new va:\n{}\nnew vb:\n{}".format(new_va,new_vb))
    #encontrar repetidos (x) e suas repectivas posicoes (i)
    repeated_a = [(x,i) for x,i in zip(new_va,range(len(va))) if new_va.count(x) > 1]
    repeated_b = [(x,i) for x,i in zip(new_vb,range(len(vb))) if new_vb.count(x) > 1]
    rn = int(len(repeated_a)/2)
    print("rn:{}".format(rn))
    for i in range(rn):
        print("switch {} / {}".format(i,rn))
        new_va[repeated_a[i][1]] = repeated_b[i+ (0 if cut >5 else rn)][0]	#se trocar sempre o primeiro 
        new_vb[repeated_b[i][1]] = repeated_a[i+ (0 if cut >5 else rn)][0]	#repetido cortes acima de 5 tendem
    print("repeated a: {}".format(repeated_a[:int(len(repeated_a))]))		#a repertir os valores dos pais
    print("repeated b: {}".format(repeated_b[:int(len(repeated_b))]))
    return(new_va,new_vb)

In [5]:
new_va,new_vb = crossover(va,vb)#[1,5,3,4,6,10,7,9,8,2])
print("new va:\n{}\nnew vb:\n{}".format(new_va,new_vb))

cut: 7
new va:
[1, 2, 3, 4, 5, 6, 7, 3, 2, 1]
new vb:
[10, 9, 8, 7, 6, 5, 4, 8, 9, 10]
rn:3
switch 0 / 3
switch 1 / 3
switch 2 / 3
repeated a: [(1, 0), (2, 1), (3, 2), (3, 7), (2, 8), (1, 9)]
repeated b: [(10, 0), (9, 1), (8, 2), (8, 7), (9, 8), (10, 9)]
new va:
[10, 9, 8, 4, 5, 6, 7, 3, 2, 1]
new vb:
[1, 2, 3, 7, 6, 5, 4, 8, 9, 10]


In [6]:
def inverse(vec):
    inf = int(random()*len(vec))
    part = list(vec[inf:])
    part.reverse()
    return vec[:inf]+part

In [7]:
def swap (vec):
    n_vec = list(vec)
    p1 = int(random()*len(vec))
    p2 = int(random()*len(vec))
    v1 = vec[p1]
    v2 = vec[p2]
    print("swap {} and {}".format(v1,v2))
    n_vec[p1] = v2
    n_vec[p2] = v1
    return n_vec

In [8]:
def insertion(vec):
    inf = int(random()*len(vec))
    part = vec[inf:]
    part = part[1:] + part[:1]
    print(part)
    return vec[:inf]+part

In [9]:
def mutation(vec,p):#percentual
    if random() > p:
        return vec
    typ = random()
    if(typ < 1/3):
        print("inverse")
        vec = inverse(vec)
    elif(typ < 2/3):
        print("swap")
        vec = swap(vec)
    else:
        print("insertion")
        vec = insertion(vec)
    return vec
    
#mutation(va,0.7)
print("Original:")
print(va)
print("Inverse:")
print(inverse(va))
print("Swap:")
print(swap(va))
print("Insertion")
print(insertion(va))

Original:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Inverse:
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
Swap:
swap 1 and 8
[8, 2, 3, 4, 5, 6, 7, 1, 9, 10]
Insertion
[3, 4, 5, 6, 7, 8, 9, 10, 2]
[1, 3, 4, 5, 6, 7, 8, 9, 10, 2]


In [10]:
mutation(va,0.7)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

<h1>Calculo de Coorelação:</h1>

In [11]:
def corr(x,y,p=False):
    # n
    n = len(x)
#Somatórios:
    #superiores
    xysum = np.dot(x,y) #soma dos x*y
    xsum = sum(x)
    ysum = sum(y)
    #inferiores
    #soma dos quadrados
    x2sum = np.dot(x,x) #multiplica entrada a entrada dos vetores x e ele mesmo e soma
    y2sum = sum([v*v for v in y]) #forma na unha de fazer o mesmo
    #quadrado das somas:
    xsum2 = xsum**2
    ysum2 = ysum**2
    #parte superior:
    sup = (xysum - xsum*ysum/n)
    #parte inferior:
    infe = math.sqrt ( (x2sum - xsum2/n) * (y2sum - ysum2/n) )
    corresult = sup/infe
    if(p):
        print("Taxa de correlação entre X e Y é:")
        print("{}\n".format(sup)+len(str(sup))*"-"+" =  {}".format(corresult)+"\n{}".format(infe))
    return corresult

<h2>Teste Da Correlação</h2>

In [12]:
gerax = lambda base,n,dif: [base + x*dif for x in range(n)] # modo preguiçoso de gerar n números espaçados em 0.5
#Carregar valores(teste):
x = gerax(2.5, 6,0.5)
y = [0.4,0.4,0.3,0.2,0.2,0.1]
corr(x,y,True)

Taxa de correlação entre X e Y é:
-0.5499999999999998
------------------- =  -0.9710083124552239
0.5664215155988811


-0.9710083124552239

In [13]:
#!/usr/bin/python

from pathlib import Path

directory = './nodes_links/'
allnodes = dict()
alllinks = dict()
names = list()
for path in Path(directory).iterdir():
    url = str(path)
    netname = path.name.split('_')[0]
    if(path.name.count('nodes')==1):
        p = allnodes
    else:
        p = alllinks
    try:
        item = pandas.read_csv(url)
        p.update( {netname : item })
    #    print(url+" lido")
    except:
        try:
            #mudar o encoding para os caracteres
            item = pandas.read_csv(url,encoding="iso-8859-1")
            p.update( {netname : item })
        #    print(url+" lido")
        except:
            print("!!! não foi possivel ler > "+name+" < !!!")
            pass
    if names.count(netname) == 0:
        names.append(netname) 


In [14]:
print(names)

netlinks = alllinks['portugal']
netnodes = allnodes['portugal']

['canarie', 'italy', 'vbns', 'loni', 'germany', 'geant2', 'arpanet', 'cesnet', 'newnet', 'rnpBrazil', 'pionier', 'spain', 'renater', 'lambdaRailUsa', 'metrona', 'arnes', 'bren', 'portugal', 'usaGde', 'sanet', 'nsfnet', 'austria', 'viaDatacenterNet', 'coxUsa', 'mzima', 'scteste', 'eon', 'memorexEurope', 'deutschTelecom', 'internet2Usa', 'OmnicomEurope']


In [15]:
#u = pandas.read_csv("./nodes_links/renater_links.csv")
a = netnodes['Id'].values.tolist()
print("nodes:\n{}".format(a))
print("links:\n{}".format(netlinks))

nodes:
['Alcácer_do_Sal', 'Aveiro', 'Beja', 'Braga', 'Bragança', 'Caldas_Rainha', 'Castelo_Branco', 'Coimbra', 'Elvas', 'Évora', 'Faro', 'Funchal', 'Guarda', 'Leiria', 'Lisboa', 'Ponta_Delgada', 'Portalegre', 'Portimão', 'Porto', 'Santarém', 'S_João_Madeira', 'Setúbal', 'Sines', 'Viana_do_Castelo', 'Vila_Real', 'Viseu']
links:
                From              To  Length  Capacity    Cost
0             Lisboa   Ponta_Delgada    1500         1  975000
1             Lisboa         Funchal    1050         1  682500
2      Ponta_Delgada         Funchal    1050         1  682500
3           Portimão         Funchal    1010         1  656500
4              Braga        Bragança     209         1  135850
5           Santarém      Portalegre     144         1   93600
6               Beja            Faro     140         1   91000
7           Portimão           Sines     139         1   90350
8           Santarém         Coimbra     136         1   88400
9           Bragança       Vila_Real     

In [16]:
def monta_matriz(netnodes,netlinks):
    nodes = netnodes['Id'].values.tolist()
    matrix = np.matrix(np.zeros( (len(nodes),len(nodes)),dtype=np.int ) )
    for n in nodes:
        l = netlinks.loc[netlinks['From']==n,['To']].values
        indexes = [nodes.index(x) for x in l]
        if(len(indexes) > 0):
            matrix[nodes.index(n),indexes] = 1
            matrix[indexes,nodes.index(n)] = 1 #bidirecional
    return matrix

matrix = monta_matriz(netnodes,netlinks)

print (matrix)

[[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 1 0 1 

In [17]:
# matrix[0,[a for a in range (0,len(mtx))]]
# print(matrix)

In [18]:
def criar_canais(mtx,ncanais):
    mtxc = np.matrix(np.zeros(mtx.shape), dtype=list)
    for i in range(len(mtx)):
        for j in range(len(mtx)):
            if(i<j):
                if(mtx[i,j] == 1):
                    mtxc[i,j]= [1]*ncanais
                    mtxc[j,i]= mtxc[i,j]
                else:
                    mtxc[i,j]= None
    return mtxc
canais = criar_canais(matrix,len(netnodes))

In [19]:
#nao sei se usaremos, mas tá aí
def diagonalizar(mtx):
    nova = np.matrix(np.zeros(mtx.shape), dtype=int)
    for i in range(len(mtx)):
       # print(l)
        for j in range(len(mtx)):
            if(i<j):
                nova[i,j] = mtx[i,j]
    return nova
print(diagonalizar(matrix))

[[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 

In [20]:
def calc_grau(matrix):
    soma=0
    for l in range(len(matrix)):
        for c in range(len(matrix)):
            soma += matrix[l,c]
    return soma/(len(matrix))

In [21]:
print("grau médio: {}".format(calc_grau(matrix)))

grau médio: 2.769230769230769


In [22]:
def aumentar_grau(mtx,inc_grau): #nodos = 6, p/incrementar 1 grau adicionamos 6 enlaces, para inc 0.5 add 3
    grau = calc_grau(mtx)
    mind = len(mtx)-1
    n_grau = grau
    while n_grau < mind and n_grau < grau + inc_grau:
        x,y=(None,None)
        while (x==None and y==None):
            x,y = (randint(0,mind), randint(0,mind))
            if x==y or mtx[x,y]==1:
                x,y=(None,None)
        mtx[x,y]=1
        mtx[y,x]=1 #bijetora...
        n_grau=calc_grau(mtx)

In [23]:
aumentar_grau(matrix,10)

In [24]:
print(matrix)

[[0 1 1 0 0 1 1 1 1 1 0 0 1 1 0 1 0 1 1 0 0 1 1 0 1 0]
 [1 0 0 1 0 0 1 1 0 0 1 1 0 1 0 0 0 1 1 1 0 0 0 0 0 1]
 [1 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 0 1 0]
 [0 1 0 0 1 1 1 0 0 0 0 0 1 0 1 0 1 1 1 0 1 0 1 1 0 1]
 [0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 1 1 1 1 1 1 0]
 [1 0 1 1 0 0 1 0 1 1 1 0 0 1 1 1 0 0 0 0 1 1 0 0 1 1]
 [1 1 0 1 0 1 0 0 0 1 1 1 1 1 0 0 1 1 0 1 1 1 0 0 0 1]
 [1 1 1 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 1 1 0 0 0 1 1]
 [1 0 1 0 0 1 0 1 0 1 0 1 1 0 0 1 1 0 0 1 0 0 0 0 0 0]
 [1 0 1 0 0 1 1 0 1 0 0 0 0 1 1 1 0 1 0 1 0 0 1 0 0 1]
 [0 1 1 0 1 1 1 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1 1 1 1 1]
 [0 1 1 0 0 0 1 0 1 0 0 0 1 1 1 1 0 1 0 0 0 1 0 0 1 0]
 [1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 0 1 0 0 1 1 0 0 0 0 1]
 [1 1 1 0 0 1 1 1 0 1 1 1 1 0 0 0 1 1 1 1 1 0 0 0 1 0]
 [0 0 1 1 1 1 0 1 0 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1 0 1]
 [1 0 1 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 1 0 0 1 1 1 0]
 [0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 1 0 1 1]
 [1 1 1 1 1 0 1 0 0 1 1 1 0 1 0 0 1 0 1 1 0 1 1 1 0 0]
 [1 1 1 1 

In [25]:
print("grau médio: {}".format(calc_grau(matrix)))

grau médio: 12.76923076923077


In [26]:
matrizes = dict()
channels = dict()
#montar matrizes, canais, etc...
for x in names:
    netlinks = alllinks[x]
    netnodes = allnodes[x]
    matriz = monta_matriz(netnodes,netlinks)
    matrizes.update({x:matriz})
    channels.update({x:criar_canais(matrix,len(netnodes))})
#     print("matriz {}:\n{}".format(x,matriz))

In [27]:
calc_grau(matrizes.get('cesnet'))

3.1666666666666665

In [28]:
print (matrizes.get('cesnet'))

[[0 1 1 1 0 0 0 0 0 1 1 1]
 [1 0 1 0 0 0 0 0 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 0 0 0 0 0 1]
 [0 0 0 1 0 1 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 1 1 1 0 1 1 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 0]
 [1 0 0 0 0 0 0 1 1 0 1 0]
 [1 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 0 0 0 0]]


In [29]:
# mtxt = matrizes.get('cesnet')
# aumentar_grau(mtxt,4)
# print (mtxt)
# print (calc_grau(mtxt))

In [30]:
# aumentar_grau(matrizes.get('cesnet'),1)


<h1>Dijkstra</h1>
<p>Implementação da busca pelo menor caminho</p>

In [31]:
#Matriz de Incidência
from math import inf

letra = lambda x:chr(ord('a')+x)

class BuscaMatriz():
    #matrizNova=list()
    def __init__(self,matrix):
        self.matrix=matrix
        self.custo=[inf]*matrix.size()
        self.pai=[-1]*matrix.size()
    def backtrack(self,destino):
        path = [destino]
#         print(destino)
        pai=self.pai[destino]
        if(pai!=-1):
            path = path + self.backtrack(pai)
        return path

class GraphMatrix():
    def __init__(self,first,matrix):#de certa forma isto não deveria estar aqui e desta forma
        self.actual=first
        self.matrix=matrix
        self.custo=0
        self.visited=[0]*len(matrix)
        self.visited[first]=1
#         for i,linha in enumerate(matrix):
#             print ("linha %d: %s"%(i,linha))
    def __str__(self):
        return 'teste'
    def visit(self,aresta,custo):
        if (self.visited[aresta]==1):
            return False
        self.visited[aresta]=1
        self.actual=aresta
        self.custo+=custo
        return True
    def get_actual(self):
        return self.actual
    def set_actual(self,actual):
        self.actual=actual
    def size(self):
        return len(self.matrix)
    def run(self,*reverse): #nem isto
#         print("Atualmente em %d com custo %d" % (self.actual,self.custo))
        vizinhos=self.get_vizinhos(self.actual)
#         print ("vizinhos:")
#         for vizinho in vizinhos:
#             print("numero %d custo %d" % vizinho)
        while len(vizinhos)>0:
            if reverse:
                v=vizinhos.pop()
            else:
                v=vizinhos.pop(0)
            if self.visit(*v) == True:
                return True
        return False

class AdjMatrix(GraphMatrix):
    def __init__(self,*args):
        super(AdjMatrix,self).__init__(*args)
    def get_vizinhos(self,vert):
#         print(self.matrix)
        vizinhos=[(i,ar) for i,ar in enumerate(self.matrix[vert]) if ar>0 ]
        vizinhos.sort(key=lambda tupla:tupla[1])
        return vizinhos

In [32]:
#import mtx /\
import sys
from math import inf
class Dijkstra(BuscaMatriz):
    show=lambda self:print("Custo: %s\nPai: %s\nFila %s\nAtual: %d" % (self.custo,self.pai,self.fila,self.matrix.get_actual()))
    def __init__(self,matrix):
#        self.matrix=matrix
#        self.custo=[inf]*matrix.size()
#        self.pai=[-1]*matrix.size()
        super(Dijkstra,self).__init__(matrix)
        self.fila=list(range(0,matrix.size()))
        self.fila.remove(self.matrix.get_actual())

#        self.custo[self.matrix.get_actual()]=0
    def explora(self):
        index=self.matrix.get_actual()
        if(self.custo[index]==inf):#caso seja desconexo
            self.custo[index]=0
        for vizinho in self.matrix.get_vizinhos(index):
            (vert,value)=vizinho
#             self.show()
            nvalue=value+self.custo[index]
            if nvalue < self.custo[vert]:
#                 print("Novo valor para %d: %d"%(vert,nvalue))
                self.atualiza(vert,nvalue)
    def gen_fila(self):
        for x in self.fila:
            custo=self.custo[x]
            yield (custo,x)
    def end(self):
        return self.fila==[]
    def atualiza(self,filho,valor):
        self.custo[filho]=valor
        self.pai[filho]=self.matrix.get_actual()
    def choose(self):
        fila=list()
        for a in self.gen_fila():
            fila.append(a)
        fila.sort()
#         print("\nFila em ordem de peso: %s"%(fila))
        (peso,actual)=fila.pop(0)
        
        self.matrix.set_actual(actual)
        self.fila.remove(actual)
        
def explorar_matrix(mtx):
    caminhos = dict()
    lmtx = mtx.tolist()
    for i in range(len(mtx)):
        for j in range(len(mtx)):
            if(i<j):
                di=Dijkstra(AdjMatrix(i,lmtx))
                di.explora()
                while(di.end()==False):
            #         print("==================================")
                    di.explora()
                    di.choose()
                caminhos.update({(i,j):di.backtrack(j)})
    return caminhos

In [33]:
caminhos = explorar_matrix(matrizes.get('cesnet'))

In [34]:
print(caminhos)

{(0, 1): [1, 0], (0, 2): [2, 0], (0, 3): [3, 0], (0, 4): [4, 3, 0], (0, 5): [5, 4, 3, 0], (0, 6): [6, 4, 3, 0], (0, 7): [7, 9, 0], (0, 8): [8, 9, 0], (0, 9): [9, 0], (0, 10): [10, 0], (0, 11): [11, 0], (1, 2): [2, 1], (1, 3): [3, 0, 1], (1, 4): [4, 3, 0, 1], (1, 5): [5, 4, 3, 0, 1], (1, 6): [6, 4, 3, 0, 1], (1, 7): [7, 9, 0, 1], (1, 8): [8, 9, 0, 1], (1, 9): [9, 0, 1], (1, 10): [10, 0, 1], (1, 11): [11, 0, 1], (2, 3): [3, 2], (2, 4): [4, 3, 2], (2, 5): [5, 4, 3, 2], (2, 6): [6, 4, 3, 2], (2, 7): [7, 4, 3, 2], (2, 8): [8, 9, 0, 2], (2, 9): [9, 0, 2], (2, 10): [10, 0, 2], (2, 11): [11, 0, 2], (3, 4): [4, 3], (3, 5): [5, 4, 3], (3, 6): [6, 4, 3], (3, 7): [7, 4, 3], (3, 8): [8, 7, 4, 3], (3, 9): [9, 0, 3], (3, 10): [10, 0, 3], (3, 11): [11, 3], (4, 5): [5, 4], (4, 6): [6, 4], (4, 7): [7, 4], (4, 8): [8, 7, 4], (4, 9): [9, 7, 4], (4, 10): [10, 0, 3, 4], (4, 11): [11, 3, 4], (5, 6): [6, 4, 5], (5, 7): [7, 5], (5, 8): [8, 7, 5], (5, 9): [9, 7, 5], (5, 10): [10, 9, 7, 5], (5, 11): [11, 3, 4, 5

In [35]:
# print(path)

In [36]:
print(caminhos[(2,5)])

[5, 4, 3, 2]


In [37]:
mtxt = matrizes.get('cesnet')
aumentar_grau(mtxt,4)
print (mtxt)
print (calc_grau(mtxt))

[[0 1 1 1 1 0 1 1 1 1 1 1]
 [1 0 1 0 1 0 0 0 0 0 0 1]
 [1 1 0 1 1 1 0 0 0 0 0 1]
 [1 0 1 0 1 1 1 0 1 0 1 1]
 [1 1 1 1 0 1 1 1 1 0 0 1]
 [0 0 1 1 1 0 1 1 1 0 0 1]
 [1 0 0 1 1 1 0 1 1 0 1 1]
 [1 0 0 0 1 1 1 0 1 1 1 0]
 [1 0 0 1 1 1 1 1 0 1 0 1]
 [1 0 0 0 0 0 0 1 1 0 1 1]
 [1 0 0 1 0 0 1 1 0 1 0 0]
 [1 1 1 1 1 1 1 0 1 1 0 0]]
7.166666666666667


In [38]:
caminhos = explorar_matrix(matrizes.get('cesnet'))

In [39]:
print(caminhos[(2,5)])

[5, 2]
