<h1>Correlação Entre Variáveis no Roteamento e atribuição de espectro</h1>
<p style='font-size: 20px' >Alunos: André Luiz Maso, Artur Bernardo Mallmann, Maikon Douglas Pereira e Tatiane Barbosa</p>
    
<p>&emsp;&emsp;Neste Trabalho vamos explorar qual é a correlação entre Taxa de Bloqueio (Tb = B/D), onde B é o número de bloqueios ocorridos durante o RSA (Roteamento e atribuição de espectro) e D é o número total de demandas (soma da triangular superior da matriz de demandas), e o Índice de Wiener da topologia (Soma do comprimento dos enlaces dos caminhos mais curtos)</p>

In [1]:
import numpy as np
import math
from random import *
#pandas para base de dados
import pandas

<h1>Calculo de Coorelação:</h1>

In [2]:
def corr(x,y,p=False):
    # n
    n = len(x)
#Somatórios:
    #superiores
    xysum = np.dot(x,y) #soma dos x*y
    xsum = sum(x)
    ysum = sum(y)
    #inferiores
    #soma dos quadrados
    x2sum = np.dot(x,x) #multiplica entrada a entrada dos vetores x e ele mesmo e soma
    y2sum = sum([v*v for v in y]) #forma na unha de fazer o mesmo
    #quadrado das somas:
    xsum2 = xsum**2
    ysum2 = ysum**2
#formula
    #parte superior:
    sup = (xysum - xsum*ysum/n)
    #parte inferior:
    infe = math.sqrt ( (x2sum - xsum2/n) * (y2sum - ysum2/n) )
    corresult = sup/infe
    if(p):
        print("Taxa de correlação entre [x] e [y] é:")
        print("{}\n".format(sup)+len(str(sup))*"-"+" =  {}".format(corresult)+"\n{}".format(infe))
    return corresult

<h2>Teste Da Correlação</h2>
<p>Para calcular a correlação entre os valores de duas variáveis basta entrar com dois vetores com os valores a serem comparados:
corr(vec1,vec2)</p>

In [3]:
gerax = lambda base,n,dif: [base + x*dif for x in range(n)] # modo preguiçoso de gerar n números espaçados em 0.5
#Carregar valores(teste):
x = gerax(2.5, 6,0.5)
y = [0.4,0.4,0.3,0.2,0.2,0.1]
corr(x,y,True)

Taxa de correlação entre [x] e [y] é:
-0.5499999999999998
------------------- =  -0.9710083124552239
0.5664215155988811


-0.9710083124552239

<h1>Carregamento de Dados</h1>
<p>Nesta sessão do código é feita a leitura dos arquivos .csv</p>

In [4]:
#!/usr/bin/python

from pathlib import Path

directory = './nodes_links/'
allnodes = dict()
alllinks = dict()
names = list()
for path in Path(directory).iterdir():
    url = str(path)
    netname = path.name.split('_')[0]
    if(path.name.count('nodes')==1):
        p = allnodes
    else:
        p = alllinks
    try:
        item = pandas.read_csv(url)
        p.update( {netname : item })
    #    print(url+" lido")
    except:
        try:
            #mudar o encoding para os caracteres
            item = pandas.read_csv(url,encoding="iso-8859-1")
            p.update( {netname : item })
        #    print(url+" lido")
        except:
            print("!!! não foi possivel ler > "+name+" < !!!")
            pass
    if names.count(netname) == 0:
        names.append(netname) 


<p>Todos os links e nós ficam guardados nos dicts alllinks e allnodes, e para serem lidos basta passar o prefixo dos arquivos originais entre colchetes. Estes prefixos são os nomes das nossas redes e ficam salvos no vetor names.</p>

In [5]:
print(names)

['canarie', 'italy', 'vbns', 'loni', 'germany', 'geant2', 'arpanet', 'cesnet', 'newnet', 'rnpBrazil', 'pionier', 'spain', 'renater', 'lambdaRailUsa', 'metrona', 'arnes', 'bren', 'portugal', 'usaGde', 'sanet', 'nsfnet', 'austria', 'viaDatacenterNet', 'coxUsa', 'mzima', 'scteste', 'eon', 'memorexEurope', 'deutschTelecom', 'internet2Usa', 'OmnicomEurope']


<p>Abaixo temos o exemplo do carregamento da rede cesnet:</p>

In [6]:
netlinks = alllinks['cesnet']
netnodes = allnodes['cesnet']

<p>Nos arquivos de nós temos no campo Id todos os nomes dos nós da rede, e nos links a origem e destino dos enlaces, como podemos ver abaixo:</p>

In [7]:
#u = pandas.read_csv("./nodes_links/renater_links.csv")
a = netnodes['Id'].values.tolist()
print("nodes:\n{}".format(a))
print("links:\n{}".format(netlinks))

nodes:
['Praga', 'Usti', 'Liberec', 'Hradec', 'Olomouc', 'Ostrava', 'Zlin', 'Brno', 'Jihlava', 'Budweiss', 'Pilsen', 'Pardubice']
links:
         From         To      Length  Capacity  Cost
0       Praga       Usti   44.320945        50     1
1        Usti    Liberec   57.122562        50     1
2     Liberec      Praga   57.111162        50     1
3       Praga     Pilsen  114.930257        50     1
4      Pilsen   Budweiss  123.277291        50     1
5    Budweiss      Praga  169.402099        50     1
6       Praga  Pardubice   72.350748        50     1
7   Pardubice     Hradec   69.868247        50     1
8      Hradec      Praga   91.221450        50     1
9      Hradec    Liberec   64.755029        50     1
10   Budweiss    Jihlava  106.688652        50     1
11    Jihlava       Brno   74.878684        50     1
12       Brno   Budweiss  163.463112        50     1
13    Olomouc     Hradec  136.245096        50     1
14    Olomouc       Zlin   30.591459        50     1
15       Zlin  

<h2>Gerando as matrizes de Adjacência</h2>
<p>Para montar as matrizes de adjacência consideramos a identificação numérica dos nós conforme a posição de cada um no vetor dos nós. Depois, com a ajuda da comparação de atributos da biblioteca pandas verificamos todas as origens e quais seus destinos, e assim preenchemos a matriz de adjacência.</p>
<p>A matriz de adjacência é bidirecional, para facilitar o uso com a implementação com qualquer algorítmo de busca a construção é nas diagonáis superiores e inferiores.</p>

In [8]:
def monta_matriz(netnodes,netlinks):
    nodes = netnodes['Id'].values.tolist()
    matrix = np.matrix(np.zeros( (len(nodes),len(nodes)),dtype=np.int ) )
    for n in nodes:
        l = netlinks.loc[netlinks['From']==n,['To']].values
        indexes = [nodes.index(x) for x in l]
        if(len(indexes) > 0):
            matrix[nodes.index(n),indexes] = 1
            matrix[indexes,nodes.index(n)] = 1 #bidirecional
    return matrix

matrix = monta_matriz(netnodes,netlinks)

print (matrix)

[[0 1 1 1 0 0 0 0 0 1 1 1]
 [1 0 1 0 0 0 0 0 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 0 0 0 0 0 1]
 [0 0 0 1 0 1 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 1 1 1 0 1 1 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 0]
 [1 0 0 0 0 0 0 1 1 0 1 0]
 [1 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 0 0 0 0]]


<p>Abaixo temos a construção das listas que representam os canais de comunicação dos enlaces. Estes canais são representados por 0's e 1's guardadas em listas salvas em dicts que são acessados pela tupla que representa o origem e destino.</p>

In [9]:
def criar_canais(mtx,ncanais):
    canais = dict()
#     mtxc = np.matrix(np.zeros(mtx.shape), dtype=list)
    for i in range(len(mtx)):
        for j in range(len(mtx)):
            if(i<j):
                if(mtx[i,j] == 1):
                    lista = [1]*ncanais #1 livre, 0 ocupado
                    canais.update({(i,j):lista})
                    canais.update({(j,i):lista})#mesma instancia para as duas direções
    return canais
#                    mtxc[i,j]= [1]*ncanais
#                    mtxc[j,i]= mtxc[i,j]
#                 else:
#                     mtxc[i,j]= None
#     return mtxc

<p>Como os canais são bidirecionais os mesmos canais são usados nas duas direções, ou seja, do nó 0 para o nó 9 e do nó 9 para o nó 0 a mesma instância do objeto lista é utilizado. Assim se o canal 0 é ocupado em uma direção ele também não estará disponível no inverso, como podemos ver abaixo:</p> 

In [10]:
canais_rede = criar_canais(matrix,len(netnodes))
canais_rede[(9,0)][0]=0 # ocupar canal 0 do enlace
print (canais_rede[0,9])
canais_rede[(9,0)][0]=1 # desocupar canal 0 do enlace
print (canais_rede[0,9])

[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


<p>Excluir a diagonal inferior(caso necessário):</p>

In [11]:
def diagonalizar(mtx):
    nova = np.matrix(np.zeros(mtx.shape), dtype=int)
    for i in range(len(mtx)):
       # print(l)
        for j in range(len(mtx)):
            if(i<j):
                nova[i,j] = mtx[i,j]
    return nova
# print(diagonalizar(matrix))

<h2>Calculo e Incrementação do grau</h2>
<p>Para calcular o grau médio basta calcular a quantidade de elementos não nulos na linha ou coluna de cada nó, e depois dividir pelo núme de nós.</p>
<p><i>Obs. Isso se aplica quando a matriz é bidirecional e as diagonais superior e inferior são não nulas.</i></p>

In [12]:
def calc_grau(matrix):
    soma=0
    for l in range(len(matrix)):
        for c in range(len(matrix)):
            if matrix[l,c] != 0:
                soma += 1
    return soma/(len(matrix))

In [13]:
print("grau médio: {}".format(calc_grau(matrix)))

grau médio: 3.1666666666666665


<p>Para aumentar o grau da nossa topologia basta inserir novos enlaces de forma aleatória na matriz de adjacência. Para isso adiciona-se enlaces até o grafo atingir o grau desejado</p>

In [14]:
def aumentar_grau(mtx,inc_grau): #nodos = 6, p/incrementar 1 grau adicionamos 6 enlaces, para inc 0.5 add 3
    grau = calc_grau(mtx)
    mind = len(mtx)-1
    n_grau = grau
    while n_grau < mind and n_grau < grau + inc_grau:
        x,y=(None,None)
        while (x==None and y==None):
            x,y = (randint(0,mind), randint(0,mind))
            if x==y or mtx[x,y]==1:
                x,y=(None,None)
        mtx[x,y]=1
        mtx[y,x]=1 #bijetora...
        n_grau=calc_grau(mtx)

<p><b>Antes:</b></p>

In [15]:
print(matrix)

[[0 1 1 1 0 0 0 0 0 1 1 1]
 [1 0 1 0 0 0 0 0 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 0 0 0 0 0 1]
 [0 0 0 1 0 1 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 1 1 1 0 1 1 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 0]
 [1 0 0 0 0 0 0 1 1 0 1 0]
 [1 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 0 0 0 0]]


In [16]:
aumentar_grau(matrix,5)

<p><b>Depois:</b></p>

In [17]:
print(matrix)

[[0 1 1 1 0 1 0 1 1 1 1 1]
 [1 0 1 0 0 1 0 1 1 1 0 0]
 [1 1 0 1 0 1 1 1 1 1 0 1]
 [1 0 1 0 1 0 0 0 1 1 1 1]
 [0 0 0 1 0 1 1 1 1 0 1 1]
 [1 1 1 0 1 0 1 1 1 1 1 0]
 [0 0 1 0 1 1 0 1 1 1 0 1]
 [1 1 1 0 1 1 1 0 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 1 1 0]
 [1 1 1 1 0 1 1 1 1 0 1 0]
 [1 0 0 1 1 1 0 1 1 1 0 1]
 [1 0 1 1 1 0 1 1 0 0 1 0]]


In [18]:
print("grau médio: {}".format(calc_grau(matrix)))

grau médio: 8.166666666666666


<h2>Construir todas as matrizes</h2>
<p>Nesta etapa geramos todas as matrizes à partir das informações tiradas dos arquivos nodes e links.

In [19]:
matrizes = dict()
#montar matrizes, canais, etc...
for x in names:
    netlinks = alllinks[x]
    netnodes = allnodes[x]
    matriz = monta_matriz(netnodes,netlinks)
    matrizes.update({x:matriz})
#     print("matriz {}:\n{}".format(x,matriz))

<p>Para acessar as matrizes basta passar o nome da rede entre []:</p>

In [20]:
mat=matrizes['cesnet']
print("matriz:\n")
print(mat)

matriz:

[[0 1 1 1 0 0 0 0 0 1 1 1]
 [1 0 1 0 0 0 0 0 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 0 0 0 0 0 1]
 [0 0 0 1 0 1 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 1 1 1 0 1 1 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 0]
 [1 0 0 0 0 0 0 1 1 0 1 0]
 [1 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 0 0 0 0]]


<h1>Dijkstra</h1>
<p>Implementação da busca pelo menor caminho</p>

In [21]:
#Matriz de Incidência
from math import inf

letra = lambda x:chr(ord('a')+x)

class BuscaMatriz():
    #matrizNova=list()
    def __init__(self,matrix):
        self.matrix=matrix
        self.custo=[inf]*matrix.size()
        self.pai=[-1]*matrix.size()
    def backtrack(self,destino):
        cam=list()
#         print(destino)
        pai=self.pai[destino]
        cam.append(destino)
        if(pai!=-1):
            cam = cam + self.backtrack(pai)
        return cam

class GraphMatrix():
    def __init__(self,first,matrix):#de certa forma isto não deveria estar aqui e desta forma
        self.actual=first
        self.matrix=matrix
        self.custo=0
        self.visited=[0]*len(matrix)
        self.visited[first]=1
#         for i,linha in enumerate(matrix):
#             print ("linha %d: %s"%(i,linha))
    def __str__(self):
        return 'teste'
    def visit(self,aresta,custo):
        if (self.visited[aresta]==1):
            return False
        self.visited[aresta]=1
        self.actual=aresta
        self.custo+=custo
        return True
    def get_actual(self):
        return self.actual
    def set_actual(self,actual):
        self.actual=actual
    def size(self):
        return len(self.matrix)
    def run(self,*reverse): #nem isto
#         print("Atualmente em %d com custo %d" % (self.actual,self.custo))
        vizinhos=self.get_vizinhos(self.actual)
#         print ("vizinhos:")
#         for vizinho in vizinhos:
#             print("numero %d custo %d" % vizinho)
        while len(vizinhos)>0:
            if reverse:
                v=vizinhos.pop()
            else:
                v=vizinhos.pop(0)
            if self.visit(*v) == True:
                return True
        return False

class AdjMatrix(GraphMatrix):
    def __init__(self,*args):
        super(AdjMatrix,self).__init__(*args)
    def get_vizinhos(self,vert):
#         print(self.matrix)
        vizinhos=[(i,ar) for i,ar in enumerate(self.matrix[vert]) if ar>0 ]
        vizinhos.sort(key=lambda tupla:tupla[1])
        return vizinhos

In [22]:
#import mtx /\
import sys
from math import inf
class Dijkstra(BuscaMatriz):
    show=lambda self:print("Custo: %s\nPai: %s\nFila %s\nAtual: %d" % (self.custo,self.pai,self.fila,self.matrix.get_actual()))
    def __init__(self,matrix):
        super(Dijkstra,self).__init__(matrix)
        self.fila=list(range(0,matrix.size()))
        self.fila.remove(self.matrix.get_actual())

    def explora(self):
        index=self.matrix.get_actual()
        if(self.custo[index]==inf):#caso seja desconexo
            self.custo[index]=0
        for vizinho in self.matrix.get_vizinhos(index):
            (vert,value)=vizinho
#             self.show()
            nvalue=value+self.custo[index]
            if nvalue < self.custo[vert]:
#                 print("Novo valor para %d: %d"%(vert,nvalue))
                self.atualiza(vert,nvalue)
    def gen_fila(self):
        for x in self.fila:
            custo=self.custo[x]
            yield (custo,x)
    def end(self):
        return self.fila==[]
    def atualiza(self,filho,valor):
        self.custo[filho]=valor
        self.pai[filho]=self.matrix.get_actual()
    def choose(self):
        fila=list()
        for a in self.gen_fila():
            fila.append(a)
        fila.sort()
#         print("\nFila em ordem de peso: %s"%(fila))
        (peso,actual)=fila.pop(0)
        
        self.matrix.set_actual(actual)
        self.fila.remove(actual)

<h2>Calcular as rotas</h2>
<p>Ao explorar a matriz verificamos os menores custos para comunicação entre todos os nós.</p>

Suporte a threads para acelerar o processo:

In [23]:
from threading import Lock #bloqueios mutex
import concurrent.futures #threads

mutex = Lock()

Explorar todos caminhos da árvore

In [24]:
# para cada caminho uma thread, a fim de acelerar o processo de exploracao
def explorar_caminho(ijcl):
    i,j,caminhos,lmtx=ijcl
    di=Dijkstra(AdjMatrix(i,lmtx))
    di.explora()
    while(di.end()==False):
        di.explora()
        di.choose()
    mutex.acquire()
    try:
        caminhos.update({(j,i):di.backtrack(j)})
    finally:
        mutex.release()
    print(caminhos)
    return caminhos

def explorar_matrix(mtx):
    caminhos = dict()
    #lmtx = mtx.tolist()
    lmtx = mtx
    # gera lista de entradas para as threads com todas as combinacoes de origem destino:
    t_caminhos=[(i,j,caminhos,lmtx) for i in range(len(mtx)) for j in range(len(mtx)) if i!=j]
    with concurrent.futures.ThreadPoolExecutor() as executor: # paralelizar o processo de explorar cada caminho
        executor.map(explorar_caminho,t_caminhos)
    return caminhos


In [25]:
matrix = np.matrix(matrizes.get('scteste'))#nova instancia
caminhos = explorar_matrix(matrix.tolist())

{(1, 0): [1, 0]}
{(1, 0): [1, 0], (2, 0): [2, 0]}{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0]}

{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0], (4, 0): [4, 3, 1, 0]}{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0], (4, 0): [4, 3, 1, 0], (5, 0): [5, 2, 0]}
{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0], (4, 0): [4, 3, 1, 0], (5, 0): [5, 2, 0], (0, 1): [0, 1]}

{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0], (4, 0): [4, 3, 1, 0], (5, 0): [5, 2, 0], (0, 1): [0, 1], (2, 1): [2, 0, 1]}{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0], (4, 0): [4, 3, 1, 0], (5, 0): [5, 2, 0], (0, 1): [0, 1], (2, 1): [2, 0, 1], (3, 1): [3, 1]}
{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0], (4, 0): [4, 3, 1, 0], (5, 0): [5, 2, 0], (0, 1): [0, 1], (2, 1): [2, 0, 1], (3, 1): [3, 1], (4, 1): [4, 3, 1]}
{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0], (4, 0): [4, 3, 1, 0], (5, 0): [5, 2, 0], (0, 1): [0, 1], (2, 1): [2, 0, 1], (3, 1): [3, 1], (4, 1): [4, 3, 1], (5, 1): [5, 2, 0, 1]}

{(

In [26]:
print(matrix)

[[0 1 1 0 0 0]
 [1 0 0 1 0 0]
 [1 0 0 1 0 1]
 [0 1 1 0 1 0]
 [0 0 0 1 0 1]
 [0 0 1 0 1 0]]


<p>O indice de wiener é expresso pelo comprimento de todos os caminhos curtos descobertos.</p>

In [27]:
def wiener(caminhos,mtx):
    custo = 0
    for i in range(len(mtx)):
        for j in range(len(mtx)):
            if(i<j):
                custo+= (len(caminhos[i,j]) -1)
    return custo

In [28]:
print(caminhos)
print("Índice Wiener: {}".format(wiener(caminhos,matrix.tolist())),file=sys.stderr)

{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0], (4, 0): [4, 3, 1, 0], (5, 0): [5, 2, 0], (0, 1): [0, 1], (2, 1): [2, 0, 1], (3, 1): [3, 1], (4, 1): [4, 3, 1], (5, 1): [5, 2, 0, 1], (0, 2): [0, 2], (1, 2): [1, 0, 2], (3, 2): [3, 2], (4, 2): [4, 3, 2], (5, 2): [5, 2], (0, 3): [0, 1, 3], (1, 3): [1, 3], (2, 3): [2, 3], (4, 3): [4, 3], (5, 3): [5, 2, 3], (0, 4): [0, 1, 3, 4], (1, 4): [1, 3, 4], (2, 4): [2, 3, 4], (3, 4): [3, 4], (5, 4): [5, 4], (0, 5): [0, 2, 5], (1, 5): [1, 0, 2, 5], (2, 5): [2, 5], (3, 5): [3, 2, 5], (4, 5): [4, 5]}


Índice Wiener: 25


In [29]:
rotear=lambda caminhos,origem,destino: [par for par in zip(caminhos[(origem,destino)],caminhos[(origem,destino)][1:]) ]

In [30]:
print(f"grau: {calc_grau(matrix)}")
print("caminho:\n{}".format(caminhos[(2,5)]))
print("enlaces:\n{}".format(rotear(caminhos,2,5)))

grau: 2.3333333333333335
caminho:
[2, 5]
enlaces:
[(2, 5)]


In [31]:
aumentar_grau(matrix,4)
print (matrix)
print (calc_grau(matrix))

[[0 1 1 1 1 1]
 [1 0 1 1 1 1]
 [1 1 0 1 1 1]
 [1 1 1 0 1 1]
 [1 1 1 1 0 1]
 [1 1 1 1 1 0]]
5.0


In [32]:
%%capture --no-stderr
# print(f'calculando indice wiener:\n {caminhos}')
caminhos = explorar_matrix(matrix.tolist())

print(f'Wiener: {wiener(caminhos,matrix)}',file=sys.stderr)

Wiener: 15


In [33]:
print("caminhos:\n{}".format(caminhos[(2,5)]))
print("enlaces:\n{}".format([par for par in zip(caminhos[(2,5)],caminhos[(2,5)][1:]) ]))

caminhos:
[2, 5]
enlaces:
[(2, 5)]


<h1>Executar os testes e simulação</h1>
<p>Por fim, executa-se diversas iterações contando o número bloqueios em cada iteração, a cada iteração o grau médio é aumentado. Por fim, calcula-se a correlação entre a taxa de bloqueio e o grau médio.</p>

In [34]:
class sim_rede():
    def __init__(self,nome,matrix_np,ncanais=-1):
        self.nome = nome
#         self.matrix = np.matrix(matrix_np) #criar uma nova cópia das originais
        if(ncanais<1):
            ncanais = int(len(matrix_np))
        self.ncanais = ncanais
        self.canais = criar_canais(matrix_np,ncanais)
        
        self.matrix = matrix_np.tolist() # nova instância do tipo lista
        self.caminhos = explorar_matrix(self.matrix) #aqui monta a árvore usando a matrix tipo lista
        self.bloqueios = 0
        self.sucesso = 0
        self.sum_demandas = 0
        
        
### 
#     def atualiza_rede(self):
#         self.caminhos = explorar_matrix(self.matrix)
        
# ERRATA: funções agora serão externas, novo grau nova classe
#        self.canais = criar_canais(self.matrix,self.ncanais) # para resetar todos eles !errata: no more!
#     def aumenta_grau(self,valor): 
#         aumentar_grau(self.matrix,valor)
#         self.atualiza_rede()
#     def calcula_grau(self):
#         return calc_grau(self.matrix)

    def testa_canais(self,enlaces):# testa os 100% ocupados para exclusão da matriz
        return sum(self.canais[no]) # Se todos os canais
    
    ########################## Conexão #################################
    # calcula os enlaces que ligam a origem ao destino
    def calc_enlaces(self,origem,destino):
        caminho = self.caminhos[(origem,destino)]
        rota = [par for par in zip(caminho,caminho[1:]) ]
        print("canais:{}, origem:{}, destino:{}, rota:{}, caminho: {}".format(self.ncanais,origem,destino,rota,caminho))
        return rota    
    
    #conecta origem e destino:
    
    def conectar(self,origem,destino):
        ok=1
        enlaces = self.calc_enlaces(origem,destino)

        caminho = self.caminhos[(origem,destino)]
        
        # excluir adjacencias relativas aos canais interrompidos e recalcular os caminhos >Sob Demanda<
        # ou seja, somente os caminhos que usam estes canais serão recalculados cada vez que necessário
#         excluir = []
        for o,d in enlaces:
            if sum(self.canais[o,d]) == 0: #se igual a 0 todos os canais do enlace estão ocupados
#                 excluir+=[(o,d),(d,o)]
                self.matrix[o][d] = 0 #exclui enlace da matriz
                self.matrix[d][o] = 0
        #atualiza caminhos
        explorar_caminho((origem,destino,self.caminhos,self.matrix))
        explorar_caminho((destino,origem,self.caminhos,self.matrix))
        
        enlaces = self.calc_enlaces(origem,destino)
        for canal in range(self.ncanais): #canal 0..n
            for o,d in enlaces: #nó do caminho
#                 print(self.canais)
                ok = ok*self.canais[(o,d)][canal] # se zero == bloqueio
#             self.sum_demandas+=1
            if ok == 1:
                for no in caminho: #no do caminho
                    try:
                        self.canais[(d,o)][canal] = 0 # marca canal do enlace como ocupado
                        self.sum_demandas+=1 #caso possível a conexão aumenta a demanda
                    except: #caminho inexistente
                        print("bloqueio ({}, {})".format(origem,destino))
                        self.bloqueios += 1
                        return (False,caminho)
                        
#                     if i > j:
#                         self.demandas[(j,i)]+=1
#                     else:
#                         self.demandas[(i,j)]+=1    
                self.sucesso += 1
                return (True,caminho)
            else:
                ok=1
        print("bloqueio ({}, {})".format(origem,destino))
        self.bloqueios += 1
        return (False,caminho)
    def wiener(self):
        return wiener(self.caminhos,self.matrix)

<p>Exemplo de uma rede pequena com dois canais com seu grau médio original provocava entre 3 e 4 bloqueio. vejamos o resultado ao incrementar duas vezes o grau.</p>

In [35]:
n='scteste'
matrix = np.matrix(matrizes.get(n)) #cópia instanciada
for i in range(3):
    print("\n===========iteracao ({})============\n".format(i))
    rede = sim_rede(n,matrix,2)
    print("wiener antes: {}".format(rede.wiener()))
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            if(i<j):
    #             print(rede.caminhos[i,j])
                rede.conectar(i,j)
    print("demandas:{}, rede:{}, bloqueios:{}, wiener: {}, grau: {}".format(rede.sum_demandas,n,rede.bloqueios,rede.wiener(),calc_grau(matrix)))
    aumentar_grau(matrix,1)
#     print("demandas(total={}):\n{}".format(rede.sum_demandas,rede.demandas))
    print("matriz:\n{}".format(matrix))


===========iteracao (0)============

{(1, 0): [1, 0]}
{(1, 0): [1, 0], (2, 0): [2, 0]}
{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0]}
{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0], (4, 0): [4, 3, 1, 0]}
{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0], (4, 0): [4, 3, 1, 0], (5, 0): [5, 2, 0]}
{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0], (4, 0): [4, 3, 1, 0], (5, 0): [5, 2, 0], (0, 1): [0, 1]}
{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0], (4, 0): [4, 3, 1, 0], (5, 0): [5, 2, 0], (0, 1): [0, 1], (2, 1): [2, 0, 1]}{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0], (4, 0): [4, 3, 1, 0], (5, 0): [5, 2, 0], (0, 1): [0, 1], (2, 1): [2, 0, 1], (3, 1): [3, 1]}
{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0], (4, 0): [4, 3, 1, 0], (5, 0): [5, 2, 0], (0, 1): [0, 1], (2, 1): [2, 0, 1], (3, 1): [3, 1], (4, 1): [4, 3, 1]}
{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0], (4, 0): [4, 3, 1, 0], (5, 0): [5, 2, 0], (0, 1): [0, 1], (2, 1): [2, 0, 1], (3, 1): [3, 1], (4, 1)

{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0], (4, 0): [4, 0], (5, 0): [5, 0], (0, 1): [0, 1], (2, 1): [2, 1], (3, 1): [3, 1], (4, 1): [4, 0, 1], (5, 1): [5, 0, 1], (0, 2): [0, 2], (1, 2): [1, 2], (3, 2): [3, 2], (4, 2): [4, 3, 2], (5, 2): [5, 2], (0, 3): [0, 1, 3], (1, 3): [1, 3], (2, 3): [2, 3], (4, 3): [4, 3], (5, 3): [5, 2, 3], (0, 4): [0, 4], (1, 4): [1, 0, 4], (2, 4): [2, 3, 4], (3, 4): [3, 4], (5, 4): [5, 4], (0, 5): [0, 5], (1, 5): [1, 0, 5], (2, 5): [2, 5], (3, 5): [3, 2, 5], (4, 5): [4, 5]}
canais:2, origem:2, destino:5, rota:[(2, 5)], caminho: [2, 5]
canais:2, origem:3, destino:4, rota:[(3, 4)], caminho: [3, 4]
{(1, 0): [1, 0], (2, 0): [2, 0], (3, 0): [3, 1, 0], (4, 0): [4, 0], (5, 0): [5, 0], (0, 1): [0, 1], (2, 1): [2, 1], (3, 1): [3, 1], (4, 1): [4, 0, 1], (5, 1): [5, 0, 1], (0, 2): [0, 2], (1, 2): [1, 2], (3, 2): [3, 2], (4, 2): [4, 3, 2], (5, 2): [5, 2], (0, 3): [0, 1, 3], (1, 3): [1, 3], (2, 3): [2, 3], (4, 3): [4, 3], (5, 3): [5, 2, 3], (0, 4): [0, 4], (1, 4): [1

<h1>Simulação e cálculo de correlação</h1>


<p>Por fim simula-se o uso da rede:</p>

In [36]:
ind_wiener = dict()
bloqs = dict()
grau = dict()
demandas = dict()
inc_grau = 1
copias = dict()
tentativas = dict()
sucesso = dict()

In [41]:
mutex2 = Lock()

def simulacao (n):
    it=0
    g=0
#    for it in range(iteracoes):
    mutex2.acquire()
    try: #evitar prints bagunçados
        print(f"começou rede {n}",file=sys.stderr)   
    finally:
        mutex2.release()
    while g < 5:
        g = calc_grau(copias[n])
        rede = sim_rede(n,copias[n])
#         print (rede.ncanais,file=sys.stderr)
#         print(copias[n],file=sys.stderr)
#         print(f'iteração: {it}',file=sys.stderr)
        ind_wiener[n] += [rede.wiener()]
        grau[n] += [calc_grau(copias[n])]
        conexoes = len(matrix)**3 # numero de interconexões é o numero de nós na portencia de 3
        for l in range(conexoes): 
            j = randint(0,len(matrix)-1)
            i = randint(0,len(matrix)-1)
            while j == i: #origem e destino devem ser diferentes
                j = randint(0,len(matrix)-1)
            rede.conectar(i,j)
        tentativas[n] += [conexoes]
        bloqs[n] += [rede.bloqueios]
        sucesso[n] += [rede.sucesso]
        demandas[n] += [rede.sum_demandas]
#         print("rede:{}, grau:{}, bloqueios:{}, wiener: {},conexões: {}, sucesso: {}".format(n,grau[n][it],rede.bloqueios,ind_wiener[n][it],conexoes,rede.sucesso),file=sys.stderr)
        if calc_grau(copias[n]) == (len(copias[n])-1): #grau máximo para
            break
        aumentar_grau(copias[n],inc_grau)
        it += 1
        
    mutex2.acquire()
    try: #evitar prints bagunçados
        print(f"rede {n} pronta",file=sys.stderr)   
    finally:
        mutex2.release()

In [47]:
%%capture --no-stderr
# teste = 'scteste'
teste = 'OmnicomEurope'
n = teste
ind_wiener.update({n:[]})
bloqs.update({n:[]})
grau.update({n:[]})
copias.update({n:np.matrix(matrizes.get(n))}) #copias das matrizes originais
demandas.update({n:[]})
tentativas.update({n:[]})
sucesso.update({n:[]})

simulacao (teste)

Começou rede OmnicomEurope
rede OmnicomEurope pronta


In [48]:
tb = []
print(f'{"wiener":>10}{"demand":>10}{"Blocks":>10}{"grau":>10}{"tentativas":>12}{"sucesso":>10}')
for a,b,c,d,e,f in zip(ind_wiener[n],demandas[n],bloqs[n],grau[n],tentativas[n],sucesso[n]):
    print (f"{a:10}{b:10}{c:10}{d:10.2f}{e:12}{f:10}")
    tb.append(c/b)
print(f"\ncorrelação de TX de bloqueio({tb})/wiener({ind_wiener[n]})")
corr(tb,ind_wiener[n],True)

    wiener    demand    Blocks      grau  tentativas   sucesso
      3166       566         0      2.84         216       216
      2009       561         0      3.84         216       216
      1727       515         0      4.84         216       216
      1550       517         3      5.84         216       213

correlação de TX de bloqueio([0.0, 0.0, 0.0, 0.005802707930367505])/wiener([3166, 2009, 1727, 1550])
Taxa de correlação entre [x] e [y] é:
-3.2669245647969056
------------------- =  -0.5162764487761903
6.327858984350343


-0.5162764487761903

In [49]:
%%capture --no-stderr
# /\ suprime a saída pode atribuir a uma var: %capture [--no-stderr] [--no-stdout] [--no-display] [output]

# Preparar as listas para receberem os resultados

for n in names:
    ind_wiener.update({n:[]})
    bloqs.update({n:[]})
    grau.update({n:[]})
    copias.update({n:np.matrix(matrizes.get(n))}) #copias das matrizes originais
    demandas.update({n:[]})
    tentativas.update({n:[]})
    sucesso.update({n:[]})
    
#simula cada rede em uma thread diferente
with concurrent.futures.ThreadPoolExecutor() as executor:
# #     executor.map(simulacao,names)
    executor.map(simulacao,[n for n in names if n!='usaGde'])
    
    
# for n in [n for n in names if n!='usaGde']: #paralelizei internamente cada rede
#     simulacao(n)

Começou rede OmnicomEuropeComeçou rede arnes
Começou rede arpanet
Começou rede austria

Começou rede bren
Começou rede canarie
Começou rede cesnet
Começou rede coxUsa
Começou rede deutschTelecom
Começou rede eon
rede cesnet pronta
Começou rede geant2
rede austria pronta
Começou rede germany
rede arpanet pronta
Começou rede internet2Usa
rede deutschTelecom pronta
Começou rede italy
rede eon pronta
Começou rede lambdaRailUsa
rede coxUsa pronta
Começou rede loni
rede bren pronta
Começou rede memorexEurope
rede arnes pronta
Começou rede metrona
rede canarie pronta
Começou rede mzima
rede italy pronta
Começou rede newnet
rede OmnicomEurope pronta
Começou rede nsfnet
rede germany pronta
Começou rede pionier
rede geant2 pronta
Começou rede portugal
rede lambdaRailUsa pronta
Começou rede renater
rede loni pronta
Começou rede rnpBrazil
rede memorexEurope pronta
Começou rede sanet
rede nsfnet pronta
Começou rede scteste
rede mzima pronta
Começou rede spain
rede metrona pronta
Começou rede vbns
r

In [56]:
names.sort()
for n in [n for n in names if n!='usaGde']:
    print ("\n{}({}):".format(n,len(matrizes[n])))
    print("wiener	demand	Blocks	grau")
    tb = []
    print(f'{"wiener":>10}{"demand":>10}{"Blocks":>10}{"grau":>10}{"tentativas":>12}{"sucesso":>10}{"tx de b":>10}')
    for a,b,c,d,e,f in zip(ind_wiener[n],demandas[n],bloqs[n],grau[n],tentativas[n],sucesso[n]):
        tb.append(c/b)
        print (f"{a:10}{b:10}{c:10}{d:10.2f}{e:12}{f:10}{c/b:10.2f}")
        
    print(f"\ncorrelação de TX de bloqueio e wiener:")
    corr(tb,ind_wiener[n],True)
#     print("\ncorrelação de TX de bloqueio/grau")
#     corr(tb,grau[n],True)
    print("=====================================")


OmnicomEurope(38):
wiener	demand	Blocks	grau
    wiener    demand    Blocks      grau  tentativas   sucesso   tx de b
      3166       556         0      2.84         216       216      0.00
      2025       533         0      3.84         216       216      0.00
      1693       509         0      4.84         216       216      0.00
      1540       526         0      5.84         216       216      0.00

correlação de TX de bloqueio e wiener:
Taxa de correlação entre [x] e [y] é:
0.0
--- =  nan
0.0

arnes(17):
wiener	demand	Blocks	grau
    wiener    demand    Blocks      grau  tentativas   sucesso   tx de b
       411       361       107      2.35         216       109      0.30
       306       461        71      3.41         216       145      0.15
       258       483        49      4.47         216       167      0.10
       236       520        38      5.53         216       178      0.07

correlação de TX de bloqueio e wiener:
Taxa de correlação entre [x] e [y] é:
23.16798266

<ipython-input-2-fbb1eca401b6>:21: RuntimeWarning: invalid value encountered in double_scalars
  corresult = sup/infe
